using Microsoft.CodeAnalysis;

namespace Daybreak.Generators;

internal static class Diagnostics
{
    public const string DependencyPropertyGenerator_NoAttributeFound = "DGD 0001";

    public static Diagnostic MissingAttributeDiagnostic(string attributeName, string attributeNamespace) => Diagnostic.Create(
                new DiagnosticDescriptor(
                    DependencyPropertyGenerator_NoAttributeFound,
                    $"{attributeNamespace}.{attributeName} not found",
                    "Could not find attribute with name {0} in namespace {1}.",
                    "Daybreak.Generators",
                    DiagnosticSeverity.Error,
                    true,
                    $"This error occurs when the attribute generated by the {nameof(GWCAEquivalentAttributeGenerator)} is not found",
                    null),
                Location.None,
                attributeName, attributeNamespace);
}
