namespace Daybreak.API.Interop.GuildWars;

[GWCAEquivalent("ControlAction")]
public enum ControlAction : uint
{
    None = 0,
    Screenshot = 0xAE,

    // Panels
    CloseAllPanels = 0x85,
    ToggleInventoryWindow = 0x8B,
    OpenScoreChart = 0xBD,
    OpenTemplateManager = 0xD3,
    OpenSaveEquipmentTemplate = 0xD4,
    OpenSaveSkillTemplate = 0xD5,
    OpenParty = 0xBF,
    OpenGuild = 0xBA,
    OpenFriends = 0xB9,
    ToggleAllBags = 0xB8,
    OpenMissionMap = 0xB6,
    OpenBag2 = 0xB5,
    OpenBag1 = 0xB4,
    OpenBelt = 0xB3,
    OpenBackpack = 0xB2,
    OpenSkillsAndAttributes = 0x8F,
    OpenQuestLog = 0x8E,
    OpenWorldMap = 0x8C,
    OpenOptions = 0x8D,
    OpenHero = 0x8A,

    // Weapon sets
    CycleEquipment = 0x86,
    ActivateWeaponSet1 = 0x81,
    ActivateWeaponSet2,
    ActivateWeaponSet3,
    ActivateWeaponSet4,

    DropItem = 0xCD, // drops bundle item >> flags, ashes, etc

    // Chat
    CharReply = 0xBE,
    OpenChat = 0xA1,
    OpenAlliance = 0x88,

    ReverseCamera = 0x90,
    StrafeLeft = 0x91,
    StrafeRight = 0x92,
    TurnLeft = 0xA2,
    TurnRight = 0xA3,
    MoveBackward = 0xAC,
    MoveForward = 0xAD,
    CancelAction = 0xAF,
    Interact = 0x80,
    ReverseDirection = 0xB1,
    Autorun = 0xB7,
    Follow = 0xCC,

    // Targeting
    TargetPartyMember1 = 0x96,
    TargetPartyMember2,
    TargetPartyMember3,
    TargetPartyMember4,
    TargetPartyMember5,
    TargetPartyMember6,
    TargetPartyMember7,
    TargetPartyMember8,
    TargetPartyMember9 = 0xC6,
    TargetPartyMember10,
    TargetPartyMember11,
    TargetPartyMember12,

    TargetNearestItem = 0xC3,
    TargetNextItem = 0xC4,
    TargetPreviousItem = 0xC5,
    TargetPartyMemberNext = 0xCA,
    TargetPartyMemberPrevious = 0xCB,
    TargetAllyNearest = 0xBC,
    ClearTarget = 0xE3,
    TargetSelf = 0xA0, // also 0x96
    TargetPriorityTarget = 0x9F,
    TargetNearestEnemy = 0x93,
    TargetNextEnemy = 0x95,
    TargetPreviousEnemy = 0x9E,

    ShowOthers = 0x89,
    ShowTargets = 0x94,

    CameraZoomIn = 0xCE,
    CameraZoomOut = 0xCF,

    // Party/Hero commands
    ClearPartyCommands = 0xDB,
    CommandParty = 0xD6,
    CommandHero1,
    CommandHero2,
    CommandHero3,
    CommandHero4 = 0x102,
    CommandHero5,
    CommandHero6,
    CommandHero7,

    OpenHero1PetCommander = 0xE0,
    OpenHero2PetCommander,
    OpenHero3PetCommander,
    OpenHero4PetCommander = 0xFE,
    OpenHero5PetCommander,
    OpenHero6PetCommander,
    OpenHero7PetCommander,
    OpenHeroCommander1 = 0xDC,
    OpenHeroCommander2,
    OpenHeroCommander3,
    OpenPetCommander,
    OpenHeroCommander4 = 0x126,
    OpenHeroCommander5,
    OpenHeroCommander6,
    OpenHeroCommander7,

    Hero1Skill1 = 0xE5,
    Hero1Skill2,
    Hero1Skill3,
    Hero1Skill4,
    Hero1Skill5,
    Hero1Skill6,
    Hero1Skill7,
    Hero1Skill8,
    Hero2Skill1,
    Hero2Skill2,
    Hero2Skill3,
    Hero2Skill4,
    Hero2Skill5,
    Hero2Skill6,
    Hero2Skill7,
    Hero2Skill8,
    Hero3Skill1,
    Hero3Skill2,
    Hero3Skill3,
    Hero3Skill4,
    Hero3Skill5,
    Hero3Skill6,
    Hero3Skill7,
    Hero3Skill8,
    Hero4Skill1 = 0x106,
    Hero4Skill2,
    Hero4Skill3,
    Hero4Skill4,
    Hero4Skill5,
    Hero4Skill6,
    Hero4Skill7,
    Hero4Skill8,
    Hero5Skill1,
    Hero5Skill2,
    Hero5Skill3,
    Hero5Skill4,
    Hero5Skill5,
    Hero5Skill6,
    Hero5Skill7,
    Hero5Skill8,
    Hero6Skill1,
    Hero6Skill2,
    Hero6Skill3,
    Hero6Skill4,
    Hero6Skill5,
    Hero6Skill6,
    Hero6Skill7,
    Hero6Skill8,
    Hero7Skill1,
    Hero7Skill2,
    Hero7Skill3,
    Hero7Skill4,
    Hero7Skill5,
    Hero7Skill6,
    Hero7Skill7,
    Hero7Skill8,

    // Skills
    UseSkill1 = 0xA4,
    UseSkill2,
    UseSkill3,
    UseSkill4,
    UseSkill5,
    UseSkill6,
    UseSkill7,
    UseSkill8
};
