namespace Daybreak.Models.Interop;

public enum TitleIds
{
    Hero,
    TyrianCartographer,
    CanthanCartographer,
    Gladiator,
    Champion,
    Kurzick,
    Luxon,
    Drunkard,
    Deprecated_SkillHunter, // Pre hard mode update version
    Survivor,
    KindOfABigDeal,
    Deprecated_TreasureHunter, // Old title, non-account bound
    Deprecated_Wisdom, // Old title, non-account bound
    ProtectorTyria,
    ProtectorCantha,
    Lucky,
    Unlucky,
    Sunspear,
    ElonianCartographer,
    ProtectorElona,
    Lightbringer,
    LegendaryDefenderOfAscalon,
    Commander,
    Gamer,
    SkillHunterTyria,
    VanquisherTyria,
    SkillHunterCantha,
    VanquisherCantha,
    SkillHunterElona,
    VanquisherElona,
    LegendaryCartographer,
    LegendaryGuardian,
    LegendarySkillHunter,
    LegendaryVanquisher,
    SweetTooth,
    GuardianTyria,
    GuardianCantha,
    GuardianElona,
    Asura,
    Deldrimor,
    EbonVanguard,
    Norn,
    MasterOfTheNorth,
    Party,
    Zaishen,
    TreasureHunter,
    Wisdom,
    Codex,
    None = 0xff
}
