using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Daybreak.Shared.Models.Guildwars;

/// <summary>
/// Definition of a Guild Wars skill. The static skill collections (per-campaign
/// lists, <see cref="AllSkills"/>, individual <c>public static readonly Skill X</c>
/// fields) are generated by <c>Tools/SkillUpdater</c> into <c>Skill.g.cs</c> from
/// the official wiki. Re-run the tool with
/// <c>dotnet run --project Tools/SkillUpdater</c> to refresh.
/// </summary>
public sealed partial class Skill : IIconUrlEntity
{
    public static readonly Skill None = new()
    {
        Id = 0,
        Name = "None",
        Elite = false,
        PvEOnly = false,
        PvP = false,
        Campaign = Campaign.None,
        Profession = Profession.None,
        Attribute = Attribute.None,
        Type = SkillType.None,
        Energy = null,
        Activation = null,
        Recharge = null,
        Overcast = null,
        Adrenaline = null,
        Sacrifice = null,
        Upkeep = null,
        Description = "",
        ConciseDescription = "",
        IconUrl = "",
    };

    private Skill() { }

    [JsonPropertyName("id")]
    public required int Id { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("profession")]
    public required Profession Profession { get; init; }

    [JsonPropertyName("attribute")]
    public required Attribute Attribute { get; init; }

    [JsonPropertyName("campaign")]
    public required Campaign Campaign { get; init; }

    [JsonPropertyName("elite")]
    public required bool Elite { get; init; }

    [JsonPropertyName("pveOnly")]
    public required bool PvEOnly { get; init; }

    [JsonPropertyName("pvp")]
    public required bool PvP { get; init; }

    [JsonPropertyName("type")]
    public required SkillType Type { get; init; }

    [JsonPropertyName("energy")]
    public required double? Energy { get; init; }

    [JsonPropertyName("activation")]
    public required double? Activation { get; init; }

    [JsonPropertyName("recharge")]
    public required double? Recharge { get; init; }

    [JsonPropertyName("overcast")]
    public required double? Overcast { get; init; }

    [JsonPropertyName("adrenaline")]
    public required double? Adrenaline { get; init; }

    [JsonPropertyName("sacrifice")]
    public required double? Sacrifice { get; init; }

    [JsonPropertyName("upkeep")]
    public required double? Upkeep { get; init; }

    [JsonPropertyName("description")]
    public required string Description { get; init; }

    [JsonPropertyName("conciseDescription")]
    public required string ConciseDescription { get; init; }

    [JsonPropertyName("iconUrl")]
    public required string IconUrl { get; init; }

    public override string ToString() => this.Name ?? nameof(Skill);

    public static bool TryParse(int id, [NotNullWhen(true)] out Skill? skill)
    {
        foreach (var candidate in AllSkills)
        {
            if (candidate.Id == id)
            {
                skill = candidate;
                return true;
            }
        }

        skill = null;
        return false;
    }

    public static bool TryParse(string name, [NotNullWhen(true)] out Skill? skill)
    {
        foreach (var candidate in AllSkills)
        {
            if (candidate.Name == name)
            {
                skill = candidate;
                return true;
            }
        }

        skill = null;
        return false;
    }

    public static Skill Parse(int id) => TryParse(id, out var skill)
        ? skill
        : throw new InvalidOperationException($"Could not find a skill with id {id}");

    public static Skill Parse(string name) => TryParse(name, out var skill)
        ? skill
        : throw new InvalidOperationException($"Could not find a skill with name {name}");
}
