// <auto-generated>
// This file was generated by the GenerateGWCABindings tool.
// Do not edit manually — re-run the generator instead.
// </auto-generated>

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Daybreak.API.Interop.GuildWars;
using Daybreak.API.Models;

[assembly: DisableRuntimeMarshalling]

namespace Daybreak.API.Interop;

/// <summary>
/// P/Invoke bindings for 227 C exports from gwca.dll.
/// Type signatures are resolved from the corresponding MSVC-decorated exports.
/// Types annotated with [GWCAEquivalent] are used in signatures where available.
/// Unmapped struct/enum types keep their C++ name to produce compile errors.
/// </summary>
internal static unsafe partial class GWCA
{
    private const string DllName = "gwca.dll";

    // GW::QuestMgr::AbandonQuest
    [LibraryImport(DllName, EntryPoint = "AbandonQuest")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool AbandonQuest(QuestContext* questContext);

    // GW::QuestMgr::AbandonQuestId | value: enum GW::Constants::QuestID (as int)
    [LibraryImport(DllName, EntryPoint = "AbandonQuestId")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool AbandonQuestId(int value);

    // GW::Trade::AcceptTrade
    [LibraryImport(DllName, EntryPoint = "AcceptTrade")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool AcceptTrade();

    // GW::FriendListMgr::AddFriend
    [LibraryImport(DllName, EntryPoint = "AddFriend")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool AddFriend(ushort* ptr1, nint ptr2);

    // GW::FriendListMgr::AddIgnore
    [LibraryImport(DllName, EntryPoint = "AddIgnore")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool AddIgnore(ushort* ptr1, nint ptr2);

    // GW::Chat::AddToChatLog
    [LibraryImport(DllName, EntryPoint = "AddToChatLog")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool AddToChatLog(ushort* ptr1, uint value2);

    // GW::UI::ButtonClick
    [LibraryImport(DllName, EntryPoint = "ButtonClick")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool ButtonClick(Frame* frame);

    // GW::Items::CanAccessXunlaiChest
    [LibraryImport(DllName, EntryPoint = "CanAccessXunlaiChest")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool CanAccessXunlaiChest();

    // GW::Map::CancelEnterChallenge
    [LibraryImport(DllName, EntryPoint = "CancelEnterChallenge")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool CancelEnterChallenge();

    // GW::Trade::CancelTrade
    [LibraryImport(DllName, EntryPoint = "CancelTrade")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool CancelTrade();

    // GW::Items::CanInteractWithItem
    [LibraryImport(DllName, EntryPoint = "CanInteractWithItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool CanInteractWithItem(Item* item);

    // GW::FriendListMgr::ChangeFriendType | friend1: TODO: map struct GW::Friend | value2: enum GW::FriendType (as int)
    // [LibraryImport(DllName, EntryPoint = "ChangeFriendType")]
    // [return: MarshalAs(UnmanagedType.U1)] internal static partial bool ChangeFriendType(Friend* friend1, int value2);

    // GW::Trade::ChangeOffer
    [LibraryImport(DllName, EntryPoint = "ChangeOffer")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool ChangeOffer();

    // GW::PlayerMgr::ChangeSecondProfession
    [LibraryImport(DllName, EntryPoint = "ChangeSecondProfession")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool ChangeSecondProfession(Profession profession1, uint value2);

    // GW::Agents::ChangeTarget
    [LibraryImport(DllName, EntryPoint = "ChangeTargetByAgent")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool ChangeTargetByAgent(AgentContext* agentContext);

    // GW::Agents::ChangeTarget
    [LibraryImport(DllName, EntryPoint = "ChangeTargetById")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool ChangeTargetById(uint value);

    // GW::CameraMgr::ComputeCamPos
    [LibraryImport(DllName, EntryPoint = "ComputeCamPos")]
    internal static partial Vector3 ComputeCamPos(float value);

    // GW::Agents::CountAllegianceInRange | value1: enum GW::Constants::Allegiance (as int)
    [LibraryImport(DllName, EntryPoint = "CountAllegianceInRange")]
    internal static partial uint CountAllegianceInRange(int value1, float value2);

    // GW::Items::CountItemByModelId
    [LibraryImport(DllName, EntryPoint = "CountItemByModelId")]
    internal static partial uint CountItemByModelId(uint value1, int value2, int value3);

    // GW::Map::CreateMapContext
    [LibraryImport(DllName, EntryPoint = "CreateMapContext")]
    internal static partial MapContext* CreateMapContext(uint value);

    // GW::Items::DepositGold
    [LibraryImport(DllName, EntryPoint = "DepositGold")]
    internal static partial uint DepositGold(uint value);

    // GW::Items::DestroyItem
    [LibraryImport(DllName, EntryPoint = "DestroyItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool DestroyItem(uint value);

    // GW::Map::DestroyMapContext
    [LibraryImport(DllName, EntryPoint = "DestroyMapContext")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool DestroyMapContext(MapContext* mapContext);

    // GW::Effects::DropBuff
    [LibraryImport(DllName, EntryPoint = "DropBuff")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool DropBuff(uint value);

    // GW::Items::DropGold
    [LibraryImport(DllName, EntryPoint = "DropGold")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool DropGold(uint value);

    // GW::Items::DropItem
    [LibraryImport(DllName, EntryPoint = "DropItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool DropItem(Item* item1, uint value2);

    // GW::UI::EncStrToUInt32
    [LibraryImport(DllName, EntryPoint = "EncStrToUInt32")]
    internal static partial uint EncStrToUInt32(ushort* ptr);

    // GW::GameThread::Enqueue | function: TODO: map struct _N::function
    // [LibraryImport(DllName, EntryPoint = "Enqueue")]
    // internal static partial void Enqueue(function function);

    // GW::Map::EnterChallenge
    [LibraryImport(DllName, EntryPoint = "EnterChallenge")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool EnterChallenge();

    // GW::Items::EquipItem
    [LibraryImport(DllName, EntryPoint = "EquipItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool EquipItem(Item* item1, uint value2);

    // GW::QuestMgr::GetActiveQuest
    [LibraryImport(DllName, EntryPoint = "GetActiveQuest")]
    internal static partial QuestContext* GetActiveQuest();

    // GW::QuestMgr::GetActiveQuestId | returns enum GW::Constants::QuestID (as int)
    [LibraryImport(DllName, EntryPoint = "GetActiveQuestId")]
    internal static partial int GetActiveQuestId();

    // GW::PlayerMgr::GetActiveTitle
    [LibraryImport(DllName, EntryPoint = "GetActiveTitle")]
    internal static partial TitleContext* GetActiveTitle();

    // GW::PlayerMgr::GetActiveTitleId | returns enum GW::Constants::TitleID (as int)
    [LibraryImport(DllName, EntryPoint = "GetActiveTitleId")]
    internal static partial int GetActiveTitleId();

    // GW::Agents::GetAgentByID
    [LibraryImport(DllName, EntryPoint = "GetAgentByID")]
    internal static partial AgentContext* GetAgentByID(uint value);

    // GW::Effects::GetAgentEffectsArray
    [LibraryImport(DllName, EntryPoint = "GetAgentEffectsArray")]
    internal static partial AgentEffects* GetAgentEffectsArray(uint value);

    // GW::Agents::GetAgentEncName
    [LibraryImport(DllName, EntryPoint = "GetAgentEncNameByAgent")]
    internal static partial ushort* GetAgentEncNameByAgent(AgentContext* agentContext);

    // GW::Agents::GetAgentEncName
    [LibraryImport(DllName, EntryPoint = "GetAgentEncNameById")]
    internal static partial ushort* GetAgentEncNameById(uint value);

    // GW::Agents::GetAgentIdByLoginNumber
    [LibraryImport(DllName, EntryPoint = "GetAgentIdByLoginNumber")]
    internal static partial uint GetAgentIdByLoginNumber(uint value);

    // GW::Effects::GetAlcoholLevel
    [LibraryImport(DllName, EntryPoint = "GetAlcoholLevel")]
    internal static partial uint GetAlcoholLevel();

    // GW::Agents::GetAmountOfPlayersInInstance
    [LibraryImport(DllName, EntryPoint = "GetAmountOfPlayersInInstance")]
    internal static partial uint GetAmountOfPlayersInInstance();

    // GW::SkillbarMgr::GetAttributeConstantData
    [LibraryImport(DllName, EntryPoint = "GetAttributeConstantData")]
    internal static partial AttributeInfo* GetAttributeConstantData(AttributeContext attributeContext);

    // GW::Items::GetBag
    [LibraryImport(DllName, EntryPoint = "GetBag")]
    internal static partial Bag* GetBag(Bag bag);

    // GW::Items::GetBagByIndex
    [LibraryImport(DllName, EntryPoint = "GetBagByIndex")]
    internal static partial Bag* GetBagByIndex(uint value);

    // GW::CameraMgr::GetCamera | returns TODO: map struct GW::Camera
    // [LibraryImport(DllName, EntryPoint = "GetCamera")]
    // internal static partial Camera* GetCamera();

    // GW::CameraMgr::GetCameraUnlock
    [LibraryImport(DllName, EntryPoint = "GetCameraUnlock")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetCameraUnlock();

    // GW::Chat::GetChannelColors
    [LibraryImport(DllName, EntryPoint = "GetChannelColors")]
    internal static partial void GetChannelColors(Channel channel1, uint* ptr2, nint ptr3);

    // GW::Chat::GetChannel
    [LibraryImport(DllName, EntryPoint = "GetChannelFromChar")]
    internal static partial Channel GetChannelFromChar(byte value);

    // GW::Chat::GetChannel
    [LibraryImport(DllName, EntryPoint = "GetChannelFromWChar")]
    internal static partial Channel GetChannelFromWChar(ushort value);

    // GW::Chat::GetChatLog | returns TODO: map struct GW::Chat::ChatBuffer
    // [LibraryImport(DllName, EntryPoint = "GetChatLog")]
    // internal static partial ChatBuffer* GetChatLog();

    // GW::UI::GetChildFrame
    [LibraryImport(DllName, EntryPoint = "GetChildFrame")]
    internal static partial Frame* GetChildFrame(Frame* frame1, uint value2);

    // GW::UI::GetCommandLinePref
    [LibraryImport(DllName, EntryPoint = "GetCommandLinePref_String")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetCommandLinePref_String(ushort* ptr1, uint* ptr2);

    // GW::UI::GetCommandLinePref
    [LibraryImport(DllName, EntryPoint = "GetCommandLinePref_UInt")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetCommandLinePref_UInt(ushort* ptr1, uint* ptr2);

    // GW::Items::GetCompositeModelInfo | returns TODO: map struct GW::CompositeModelInfo
    // [LibraryImport(DllName, EntryPoint = "GetCompositeModelInfo")]
    // internal static partial CompositeModelInfo* GetCompositeModelInfo(uint value);

    // GW::Agents::GetControlledCharacter
    [LibraryImport(DllName, EntryPoint = "GetControlledCharacter")]
    internal static partial AgentLivingContext* GetControlledCharacter();

    // GW::Agents::GetControlledCharacterId
    [LibraryImport(DllName, EntryPoint = "GetControlledCharacterId")]
    internal static partial uint GetControlledCharacterId();

    // GW::GuildMgr::GetCurrentGH | returns TODO: map struct GW::Guild
    // [LibraryImport(DllName, EntryPoint = "GetCurrentGH")]
    // internal static partial Guild* GetCurrentGH();

    // GW::Chat::GetDefaultColors
    [LibraryImport(DllName, EntryPoint = "GetDefaultColors")]
    internal static partial void GetDefaultColors(Channel channel1, uint* ptr2, nint ptr3);

    // GW::Map::GetDistrict
    [LibraryImport(DllName, EntryPoint = "GetDistrict")]
    internal static partial int GetDistrict();

    // GW::Effects::GetDrunkAf
    [LibraryImport(DllName, EntryPoint = "GetDrunkAf")]
    internal static partial void GetDrunkAf(float value1, uint value2);

    // GW::Items::GetEquipmentVisibility | returns enum GW::EquipmentStatus (as int) | value: enum GW::EquipmentType (as int)
    [LibraryImport(DllName, EntryPoint = "GetEquipmentVisibility")]
    internal static partial int GetEquipmentVisibility(int value);

    // GW::Agents::GetEvaluatedTargetId
    [LibraryImport(DllName, EntryPoint = "GetEvaluatedTargetId")]
    internal static partial uint GetEvaluatedTargetId();

    // GW::CameraMgr::GetFieldOfView
    [LibraryImport(DllName, EntryPoint = "GetFieldOfView")]
    internal static partial float GetFieldOfView();

    // GW::Map::GetFoesKilled
    [LibraryImport(DllName, EntryPoint = "GetFoesKilled")]
    internal static partial uint GetFoesKilled();

    // GW::Map::GetFoesToKill
    [LibraryImport(DllName, EntryPoint = "GetFoesToKill")]
    internal static partial uint GetFoesToKill();

    // GW::UI::GetFrameById
    [LibraryImport(DllName, EntryPoint = "GetFrameById")]
    internal static partial Frame* GetFrameById(uint value);

    // GW::UI::GetFrameByLabel
    [LibraryImport(DllName, EntryPoint = "GetFrameByLabel")]
    internal static partial Frame* GetFrameByLabel(ushort* ptr);

    // GW::UI::GetFrameContext
    [LibraryImport(DllName, EntryPoint = "GetFrameContext")]
    internal static partial void* GetFrameContext(Frame* frame);

    // GW::FriendListMgr::GetFriend | returns TODO: map struct GW::Friend
    // [LibraryImport(DllName, EntryPoint = "GetFriendByIndex")]
    // internal static partial Friend* GetFriendByIndex(uint value);

    // GW::FriendListMgr::GetFriend | returns TODO: map struct GW::Friend | value3: enum GW::FriendType (as int)
    // [LibraryImport(DllName, EntryPoint = "GetFriendByName")]
    // internal static partial Friend* GetFriendByName(ushort* ptr1, nint ptr2, int value3);

    // GW::FriendListMgr::GetFriend | returns TODO: map struct GW::Friend
    // [LibraryImport(DllName, EntryPoint = "GetFriendByUuid")]
    // internal static partial Friend* GetFriendByUuid(byte* ptr);

    // GW::FriendListMgr::GetFriendList | returns TODO: map struct GW::FriendList
    // [LibraryImport(DllName, EntryPoint = "GetFriendList")]
    // internal static partial FriendList* GetFriendList();

    // GW::Items::GetGoldAmountInStorage
    [LibraryImport(DllName, EntryPoint = "GetGoldAmountInStorage")]
    internal static partial uint GetGoldAmountInStorage();

    // GW::Items::GetGoldAmountOnCharacter
    [LibraryImport(DllName, EntryPoint = "GetGoldAmountOnCharacter")]
    internal static partial uint GetGoldAmountOnCharacter();

    // GW::GuildMgr::GetGuildInfo | returns TODO: map struct GW::Guild
    // [LibraryImport(DllName, EntryPoint = "GetGuildInfo")]
    // internal static partial Guild* GetGuildInfo(uint value);

    // GW::Agents::GetHeroAgentID
    [LibraryImport(DllName, EntryPoint = "GetHeroAgentID")]
    internal static partial uint GetHeroAgentID(uint value);

    // GW::SkillbarMgr::GetHeroSkillbar
    [LibraryImport(DllName, EntryPoint = "GetHeroSkillbar")]
    internal static partial SkillbarContext* GetHeroSkillbar(uint value);

    // GW::Items::GetHoveredItem
    [LibraryImport(DllName, EntryPoint = "GetHoveredItem")]
    internal static partial Item* GetHoveredItem();

    // GW::SkillbarMgr::GetHoveredSkill | returns TODO: map struct GW::Skill
    // [LibraryImport(DllName, EntryPoint = "GetHoveredSkill")]
    // internal static partial Skill* GetHoveredSkill();

    // GW::Map::GetInstanceTime
    [LibraryImport(DllName, EntryPoint = "GetInstanceTime")]
    internal static partial uint GetInstanceTime();

    // GW::Map::GetInstanceType
    [LibraryImport(DllName, EntryPoint = "GetInstanceType")]
    internal static partial InstanceType GetInstanceType();

    // GW::Items::GetInventory
    [LibraryImport(DllName, EntryPoint = "GetInventory")]
    internal static partial Inventory* GetInventory();

    // GW::Agents::GetIsAgentTargettable
    [LibraryImport(DllName, EntryPoint = "GetIsAgentTargettable")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsAgentTargettable(AgentContext* agentContext);

    // GW::Map::GetIsInCinematic
    [LibraryImport(DllName, EntryPoint = "GetIsInCinematic")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsInCinematic();

    // GW::Map::GetIsMapLoaded
    [LibraryImport(DllName, EntryPoint = "GetIsMapLoaded")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsMapLoaded();

    // GW::Map::GetIsMapUnlocked | value: enum GW::Constants::MapID (as int)
    [LibraryImport(DllName, EntryPoint = "GetIsMapUnlocked")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsMapUnlocked(int value);

    // GW::Map::GetIsObserving
    [LibraryImport(DllName, EntryPoint = "GetIsObserving")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsObserving();

    // GW::UI::GetIsShiftScreenShot
    [LibraryImport(DllName, EntryPoint = "GetIsShiftScreenShot")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsShiftScreenShot();

    // GW::SkillbarMgr::GetIsSkillLearnt | value: enum GW::Constants::SkillID (as int)
    [LibraryImport(DllName, EntryPoint = "GetIsSkillLearnt")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsSkillLearnt(int value);

    // GW::SkillbarMgr::GetIsSkillUnlocked | value: enum GW::Constants::SkillID (as int)
    [LibraryImport(DllName, EntryPoint = "GetIsSkillUnlocked")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsSkillUnlocked(int value);

    // GW::Items::GetIsStorageOpen
    [LibraryImport(DllName, EntryPoint = "GetIsStorageOpen")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsStorageOpen();

    // GW::Chat::GetIsTyping
    [LibraryImport(DllName, EntryPoint = "GetIsTyping")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsTyping();

    // GW::UI::GetIsUIDrawn
    [LibraryImport(DllName, EntryPoint = "GetIsUIDrawn")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsUIDrawn();

    // GW::UI::GetIsWorldMapShowing
    [LibraryImport(DllName, EntryPoint = "GetIsWorldMapShowing")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetIsWorldMapShowing();

    // GW::Items::GetItemById
    [LibraryImport(DllName, EntryPoint = "GetItemById")]
    internal static partial Item* GetItemById(uint value);

    // GW::Items::GetItemByModelId
    [LibraryImport(DllName, EntryPoint = "GetItemByModelId")]
    internal static partial Item* GetItemByModelId(uint value1, int value2, int value3);

    // GW::Items::GetItemBySlot
    [LibraryImport(DllName, EntryPoint = "GetItemBySlot")]
    internal static partial Item* GetItemBySlot(Bag* bag1, uint value2);

    // GW::Items::GetItemFormula | returns TODO: map struct GW::ItemFormula
    // [LibraryImport(DllName, EntryPoint = "GetItemFormula")]
    // internal static partial ItemFormula* GetItemFormula(Item* item);

    // GW::Map::GetLanguage
    [LibraryImport(DllName, EntryPoint = "GetLanguage")]
    internal static partial Language GetLanguage();

    // GW::Agents::GetMapAgentByID
    [LibraryImport(DllName, EntryPoint = "GetMapAgentByID")]
    internal static partial MapAgentContext* GetMapAgentByID(uint value);

    // GW::Map::GetMapID | returns enum GW::Constants::MapID (as int)
    [LibraryImport(DllName, EntryPoint = "GetMapID")]
    internal static partial int GetMapID();

    // GW::Map::GetMapInfo | value: enum GW::Constants::MapID (as int)
    [LibraryImport(DllName, EntryPoint = "GetMapInfo")]
    internal static partial AreaInfo* GetMapInfo(int value);

    // GW::Items::GetMaterialSlot | returns enum GW::Constants::MaterialSlot (as int)
    [LibraryImport(DllName, EntryPoint = "GetMaterialSlot")]
    internal static partial int GetMaterialSlot(Item* item);

    // GW::Items::GetMaterialStorageStackSize
    [LibraryImport(DllName, EntryPoint = "GetMaterialStorageStackSize")]
    internal static partial uint GetMaterialStorageStackSize();

    // GW::Map::GetMissionMapContext | returns TODO: map struct GW::MissionMapContext
    // [LibraryImport(DllName, EntryPoint = "GetMissionMapContext")]
    // internal static partial MissionMapContext* GetMissionMapContext();

    // GW::FriendListMgr::GetMyStatus | returns enum GW::FriendStatus (as int)
    [LibraryImport(DllName, EntryPoint = "GetMyStatus")]
    internal static partial int GetMyStatus();

    // GW::Agents::GetNPCByID
    [LibraryImport(DllName, EntryPoint = "GetNPCByID")]
    internal static partial NpcContext* GetNPCByID(uint value);

    // GW::FriendListMgr::GetNumberOfFriends | value: enum GW::FriendType (as int)
    [LibraryImport(DllName, EntryPoint = "GetNumberOfFriends")]
    internal static partial uint GetNumberOfFriends(int value);

    // GW::FriendListMgr::GetNumberOfIgnores
    [LibraryImport(DllName, EntryPoint = "GetNumberOfIgnores")]
    internal static partial uint GetNumberOfIgnores();

    // GW::FriendListMgr::GetNumberOfPartners
    [LibraryImport(DllName, EntryPoint = "GetNumberOfPartners")]
    internal static partial uint GetNumberOfPartners();

    // GW::FriendListMgr::GetNumberOfTraders
    [LibraryImport(DllName, EntryPoint = "GetNumberOfTraders")]
    internal static partial uint GetNumberOfTraders();

    // GW::Agents::GetObservingId
    [LibraryImport(DllName, EntryPoint = "GetObservingId")]
    internal static partial uint GetObservingId();

    // GW::UI::GetParentFrame
    [LibraryImport(DllName, EntryPoint = "GetParentFrame")]
    internal static partial Frame* GetParentFrame(Frame* frame);

    // GW::PlayerMgr::GetPlayerAgentId
    [LibraryImport(DllName, EntryPoint = "GetPlayerAgentId")]
    internal static partial uint GetPlayerAgentId(uint value);

    // GW::Effects::GetPlayerBuffBySkillId | value: enum GW::Constants::SkillID (as int)
    [LibraryImport(DllName, EntryPoint = "GetPlayerBuffBySkillId")]
    internal static partial Buff* GetPlayerBuffBySkillId(int value);

    // GW::Agents::GetPlayerByID
    [LibraryImport(DllName, EntryPoint = "GetPlayerByID")]
    internal static partial AgentContext* GetPlayerByID(uint value);

    // GW::Effects::GetPlayerEffectBySkillId | value: enum GW::Constants::SkillID (as int)
    [LibraryImport(DllName, EntryPoint = "GetPlayerEffectBySkillId")]
    internal static partial Effect* GetPlayerEffectBySkillId(int value);

    // GW::Effects::GetPlayerEffectsArray
    [LibraryImport(DllName, EntryPoint = "GetPlayerEffectsArray")]
    internal static partial AgentEffects* GetPlayerEffectsArray();

    // GW::GuildMgr::GetPlayerGuild | returns TODO: map struct GW::Guild
    // [LibraryImport(DllName, EntryPoint = "GetPlayerGuild")]
    // internal static partial Guild* GetPlayerGuild();

    // GW::GuildMgr::GetPlayerGuildAnnouncement
    [LibraryImport(DllName, EntryPoint = "GetPlayerGuildAnnouncement")]
    internal static partial ushort* GetPlayerGuildAnnouncement();

    // GW::GuildMgr::GetPlayerGuildAnnouncer
    [LibraryImport(DllName, EntryPoint = "GetPlayerGuildAnnouncer")]
    internal static partial ushort* GetPlayerGuildAnnouncer();

    // GW::GuildMgr::GetPlayerGuildIndex
    [LibraryImport(DllName, EntryPoint = "GetPlayerGuildIndex")]
    internal static partial uint GetPlayerGuildIndex();

    // GW::Agents::GetPlayerNameByLoginNumber
    [LibraryImport(DllName, EntryPoint = "GetPlayerNameByLoginNumber")]
    internal static partial ushort* GetPlayerNameByLoginNumber(uint value);

    // GW::PlayerMgr::GetPlayerNumber
    [LibraryImport(DllName, EntryPoint = "GetPlayerNumber")]
    internal static partial uint GetPlayerNumber();

    // GW::SkillbarMgr::GetPlayerSkillbar
    [LibraryImport(DllName, EntryPoint = "GetPlayerSkillbar")]
    internal static partial SkillbarContext* GetPlayerSkillbar();

    // GW::UI::GetPreference | value: enum GW::UI::EnumPreference (as int)
    [LibraryImport(DllName, EntryPoint = "GetPreference_Enum")]
    internal static partial uint GetPreference_Enum(int value);

    // GW::UI::GetPreference | value: enum GW::UI::FlagPreference (as int)
    [LibraryImport(DllName, EntryPoint = "GetPreference_Flag")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetPreference_Flag(int value);

    // GW::UI::GetPreference | value: enum GW::UI::NumberPreference (as int)
    [LibraryImport(DllName, EntryPoint = "GetPreference_Number")]
    internal static partial uint GetPreference_Number(int value);

    // GW::UI::GetPreference | value: enum GW::UI::StringPreference (as int)
    [LibraryImport(DllName, EntryPoint = "GetPreference_String")]
    internal static partial ushort* GetPreference_String(int value);

    // GW::Items::GetPvPItemInfo | returns TODO: map struct GW::PvPItemInfo
    // [LibraryImport(DllName, EntryPoint = "GetPvPItemInfo")]
    // internal static partial PvPItemInfo* GetPvPItemInfo(uint value);

    // GW::Items::GetPvPItemUpgrade | returns TODO: map struct GW::PvPItemUpgradeInfo
    // [LibraryImport(DllName, EntryPoint = "GetPvPItemUpgrade")]
    // internal static partial PvPItemUpgradeInfo* GetPvPItemUpgrade(uint value);

    // GW::Items::GetPvPItemUpgradeEncodedDescription
    [LibraryImport(DllName, EntryPoint = "GetPvPItemUpgradeEncodedDescription")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetPvPItemUpgradeEncodedDescription(uint value1, void* ptr2);

    // GW::Items::GetPvPItemUpgradeEncodedName
    [LibraryImport(DllName, EntryPoint = "GetPvPItemUpgradeEncodedName")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetPvPItemUpgradeEncodedName(uint value1, void* ptr2);

    // GW::QuestMgr::GetQuest | value: enum GW::Constants::QuestID (as int)
    [LibraryImport(DllName, EntryPoint = "GetQuest")]
    internal static partial QuestContext* GetQuest(int value);

    // GW::QuestMgr::GetQuestEntryGroupName | value1: enum GW::Constants::QuestID (as int)
    [LibraryImport(DllName, EntryPoint = "GetQuestEntryGroupName")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool GetQuestEntryGroupName(int value1, ushort* ptr2, uint value3);

    // GW::QuestMgr::GetQuestLog
    [LibraryImport(DllName, EntryPoint = "GetQuestLog")]
    internal static partial GuildWarsArray<QuestContext>* GetQuestLog();

    // GW::Map::GetRegion
    [LibraryImport(DllName, EntryPoint = "GetRegion")]
    internal static partial ServerRegion GetRegion();

    // GW::UI::GetRootFrame
    [LibraryImport(DllName, EntryPoint = "GetRootFrame")]
    internal static partial Frame* GetRootFrame();

    // GW::Items::GetSalvageSessionInfo | returns TODO: map struct GW::SalvageSessionInfo
    // [LibraryImport(DllName, EntryPoint = "GetSalvageSessionInfo")]
    // internal static partial SalvageSessionInfo* GetSalvageSessionInfo();

    // GW::SkillbarMgr::GetSkillbar
    [LibraryImport(DllName, EntryPoint = "GetSkillbar")]
    internal static partial SkillbarContext* GetSkillbar(uint value);

    // GW::SkillbarMgr::GetSkillConstantData | returns TODO: map struct GW::Skill | value: enum GW::Constants::SkillID (as int)
    // [LibraryImport(DllName, EntryPoint = "GetSkillConstantData")]
    // internal static partial Skill* GetSkillConstantData(int value);

    // GW::SkillbarMgr::GetSkillSlot | value: enum GW::Constants::SkillID (as int)
    [LibraryImport(DllName, EntryPoint = "GetSkillSlot")]
    internal static partial int GetSkillSlot(int value);

    // GW::Items::GetStoragePage | returns enum GW::Constants::StoragePane (as int)
    [LibraryImport(DllName, EntryPoint = "GetStoragePage")]
    internal static partial int GetStoragePage();

    // GW::Agents::GetTargetAsAgentLiving
    [LibraryImport(DllName, EntryPoint = "GetTargetAsAgentLiving")]
    internal static partial AgentLivingContext* GetTargetAsAgentLiving();

    // GW::Agents::GetTargetId
    [LibraryImport(DllName, EntryPoint = "GetTargetId")]
    internal static partial uint GetTargetId();

    // GW::UI::GetTextLanguage
    [LibraryImport(DllName, EntryPoint = "GetTextLanguage")]
    internal static partial Language GetTextLanguage();

    // GW::PlayerMgr::GetTitleData | value: enum GW::Constants::TitleID (as int)
    [LibraryImport(DllName, EntryPoint = "GetTitleData")]
    internal static partial TitleClientData* GetTitleData(int value);

    // GW::PlayerMgr::GetTitleTrack | value: enum GW::Constants::TitleID (as int)
    [LibraryImport(DllName, EntryPoint = "GetTitleTrack")]
    internal static partial TitleContext* GetTitleTrack(int value);

    // GW::UI::GetWindowPosition | returns TODO: map struct GW::UI::WindowPosition | value: enum GW::UI::WindowID (as int)
    // [LibraryImport(DllName, EntryPoint = "GetWindowPosition")]
    // internal static partial WindowPosition* GetWindowPosition(int value);

    // GW::Map::GetWorldMapContext | returns TODO: map struct GW::WorldMapContext
    // [LibraryImport(DllName, EntryPoint = "GetWorldMapContext")]
    // internal static partial WorldMapContext* GetWorldMapContext();

    // GW::CameraMgr::GetYaw
    [LibraryImport(DllName, EntryPoint = "GetYaw")]
    internal static partial float GetYaw();

    // Fallback: GWCAVersion (data export)
    internal static byte* GWCAVersion
    {
        get
        {
            var lib = NativeLibrary.Load(DllName);
            var addr = NativeLibrary.GetExport(lib, "GWCAVersion");
            return (byte*)addr;
        }
    }

    // GW::Items::IdentifyItem
    [LibraryImport(DllName, EntryPoint = "IdentifyItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool IdentifyItem(uint value1, uint value2);

    // GW::Agents::InteractAgent
    [LibraryImport(DllName, EntryPoint = "InteractAgent")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool InteractAgent(AgentContext* agentContext1, [MarshalAs(UnmanagedType.U1)] bool flag2);

    // GW::UI::IsInControllerCursorMode
    [LibraryImport(DllName, EntryPoint = "IsInControllerCursorMode")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool IsInControllerCursorMode();

    // GW::UI::IsInControllerMode
    [LibraryImport(DllName, EntryPoint = "IsInControllerMode")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool IsInControllerMode();

    // GW::GameThread::IsInGameThread
    [LibraryImport(DllName, EntryPoint = "IsInGameThread")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool IsInGameThread();

    // GW::Trade::IsItemOffered | returns TODO: map struct GW::TradeItem
    // [LibraryImport(DllName, EntryPoint = "IsItemOffered")]
    // internal static partial TradeItem* IsItemOffered(uint value);

    // GW::Agents::IsObserving
    [LibraryImport(DllName, EntryPoint = "IsObserving")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool IsObserving();

    // GW::UI::IsValidEncStr
    [LibraryImport(DllName, EntryPoint = "IsValidEncStr")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool IsValidEncStr(ushort* ptr);

    // GW::Map::LanguageFromDistrict
    [LibraryImport(DllName, EntryPoint = "LanguageFromDistrict")]
    internal static partial Language LanguageFromDistrict(District district);

    // GW::GuildMgr::LeaveGH
    [LibraryImport(DllName, EntryPoint = "LeaveGH")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool LeaveGH();

    // GW::SkillbarMgr::LoadSkillTemplate
    [LibraryImport(DllName, EntryPoint = "LoadSkillTemplateForAgent")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool LoadSkillTemplateForAgent(uint value1, SkillTemplate* skillTemplate2);

    // GW::SkillbarMgr::LoadSkillTemplate
    [LibraryImport(DllName, EntryPoint = "LoadSkillTemplateString")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool LoadSkillTemplateString(byte* ptr);

    // GW::Agents::Move
    [LibraryImport(DllName, EntryPoint = "Move")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool Move(float value1, float value2, uint value3);

    // GW::Items::MoveItem
    [LibraryImport(DllName, EntryPoint = "MoveItemToBag")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool MoveItemToBag(Item* item1, Bag* bag2, uint value3, uint value4);

    // Fallback: MoveItemToItem (from GWCA C interop header)
    [LibraryImport(DllName, EntryPoint = "MoveItemToItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool MoveItemToItem(Item* from, Item* to, uint quantity);

    // GW::Trade::OfferItem
    [LibraryImport(DllName, EntryPoint = "OfferItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool OfferItem(uint value1, uint value2);

    // GW::Trade::OpenTradeWindow
    [LibraryImport(DllName, EntryPoint = "OpenTradeWindow")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool OpenTradeWindow(uint value);

    // GW::Items::OpenXunlaiWindow
    [LibraryImport(DllName, EntryPoint = "OpenXunlaiWindow")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool OpenXunlaiWindow([MarshalAs(UnmanagedType.U1)] bool flag1, nint ptr2);

    // GW::Items::PickUpItem
    [LibraryImport(DllName, EntryPoint = "PickUpItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool PickUpItem(Item* item1, uint value2);

    // GW::Items::PingWeaponSet
    [LibraryImport(DllName, EntryPoint = "PingWeaponSet")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool PingWeaponSet(uint value1, uint value2, uint value3);

    // GW::Map::QueryAltitude
    [LibraryImport(DllName, EntryPoint = "QueryAltitude")]
    internal static partial float QueryAltitude(GamePos* gamePos1, float value2, MapContext* mapContext3);

    // GW::Map::RegionFromDistrict
    [LibraryImport(DllName, EntryPoint = "RegionFromDistrict")]
    internal static partial ServerRegion RegionFromDistrict(District district);

    // GW::PlayerMgr::RemoveActiveTitle
    [LibraryImport(DllName, EntryPoint = "RemoveActiveTitle")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool RemoveActiveTitle();

    // GW::FriendListMgr::RemoveFriend | friend: TODO: map struct GW::Friend
    // [LibraryImport(DllName, EntryPoint = "RemoveFriend")]
    // [return: MarshalAs(UnmanagedType.U1)] internal static partial bool RemoveFriend(Friend* friend);

    // Fallback: RemoveOfferedItem (from GWCA C interop header)
    [LibraryImport(DllName, EntryPoint = "RemoveOfferedItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool RemoveOfferedItem(uint slot);

    // GW::QuestMgr::RequestQuestInfo
    [LibraryImport(DllName, EntryPoint = "RequestQuestInfo")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool RequestQuestInfo(QuestContext* questContext1, [MarshalAs(UnmanagedType.U1)] bool flag2);

    // GW::QuestMgr::RequestQuestInfoId | value1: enum GW::Constants::QuestID (as int)
    [LibraryImport(DllName, EntryPoint = "RequestQuestInfoId")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool RequestQuestInfoId(int value1, [MarshalAs(UnmanagedType.U1)] bool flag2);

    // GW::Items::SalvageMaterials
    [LibraryImport(DllName, EntryPoint = "SalvageMaterials")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SalvageMaterials();

    // GW::Items::SalvageSessionCancel
    [LibraryImport(DllName, EntryPoint = "SalvageSessionCancel")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SalvageSessionCancel();

    // GW::Items::SalvageStart
    [LibraryImport(DllName, EntryPoint = "SalvageStart")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SalvageStart(uint value1, uint value2);

    // GW::UI::SelectDropdownOption
    [LibraryImport(DllName, EntryPoint = "SelectDropdownOption")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SelectDropdownOption(Frame* frame1, uint value2);

    // GW::Chat::SendChat
    [LibraryImport(DllName, EntryPoint = "SendChat")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SendChat(Channel channel1, ushort* ptr2);

    // GW::Agents::SendDialog
    [LibraryImport(DllName, EntryPoint = "SendDialog")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SendDialog(uint value);

    // GW::UI::SendUIMessage
    [LibraryImport(DllName, EntryPoint = "SendUIMessage")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SendUIMessage(UIMessage uIMessage1, void* ptr2, nint ptr3);

    // GW::Chat::SendWhisper
    [LibraryImport(DllName, EntryPoint = "SendWhisper")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SendWhisper(ushort* ptr1, nint ptr2);

    // GW::QuestMgr::SetActiveQuest
    [LibraryImport(DllName, EntryPoint = "SetActiveQuest")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetActiveQuest(QuestContext* questContext);

    // GW::QuestMgr::SetActiveQuestId | value: enum GW::Constants::QuestID (as int)
    [LibraryImport(DllName, EntryPoint = "SetActiveQuestId")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetActiveQuestId(int value);

    // GW::PlayerMgr::SetActiveTitle | value: enum GW::Constants::TitleID (as int)
    [LibraryImport(DllName, EntryPoint = "SetActiveTitle")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetActiveTitle(int value);

    // GW::UI::SetCommandLinePref
    [LibraryImport(DllName, EntryPoint = "SetCommandLinePref_String")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetCommandLinePref_String(ushort* ptr1, uint value2);

    // GW::UI::SetCommandLinePref
    [LibraryImport(DllName, EntryPoint = "SetCommandLinePref_UInt")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetCommandLinePref_UInt(ushort* ptr1, uint value2);

    // GW::Items::SetEquipmentVisibility | value1: enum GW::EquipmentType (as int) | value2: enum GW::EquipmentStatus (as int)
    [LibraryImport(DllName, EntryPoint = "SetEquipmentVisibility")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetEquipmentVisibility(int value1, int value2);

    // GW::CameraMgr::SetFieldOfView
    [LibraryImport(DllName, EntryPoint = "SetFieldOfView")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetFieldOfView(float value);

    // GW::CameraMgr::SetFog
    [LibraryImport(DllName, EntryPoint = "SetFog")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetFog([MarshalAs(UnmanagedType.U1)] bool flag);

    // GW::UI::SetFrameDisabled
    [LibraryImport(DllName, EntryPoint = "SetFrameDisabled")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetFrameDisabled(Frame* frame1, [MarshalAs(UnmanagedType.U1)] bool flag2);

    // GW::UI::SetFrameTitle
    [LibraryImport(DllName, EntryPoint = "SetFrameTitle")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetFrameTitle(Frame* frame1, ushort* ptr2);

    // GW::UI::SetFrameVisible
    [LibraryImport(DllName, EntryPoint = "SetFrameVisible")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetFrameVisible(Frame* frame1, [MarshalAs(UnmanagedType.U1)] bool flag2);

    // GW::FriendListMgr::SetFriendListStatus | value: enum GW::FriendStatus (as int)
    [LibraryImport(DllName, EntryPoint = "SetFriendListStatus")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetFriendListStatus(int value);

    // GW::CameraMgr::SetMaxDist
    [LibraryImport(DllName, EntryPoint = "SetMaxDist")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetMaxDist(float value);

    // GW::Chat::SetMessageColor
    [LibraryImport(DllName, EntryPoint = "SetMessageColor")]
    internal static partial uint SetMessageColor(Channel channel1, uint value2);

    // GW::PlayerMgr::SetPlayerName
    [LibraryImport(DllName, EntryPoint = "SetPlayerName")]
    internal static partial ushort* SetPlayerName(uint value1, ushort* ptr2);

    // GW::UI::SetPreference | value1: enum GW::UI::EnumPreference (as int)
    [LibraryImport(DllName, EntryPoint = "SetPreference_Enum")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetPreference_Enum(int value1, uint value2);

    // GW::UI::SetPreference | value1: enum GW::UI::FlagPreference (as int)
    [LibraryImport(DllName, EntryPoint = "SetPreference_Flag")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetPreference_Flag(int value1, [MarshalAs(UnmanagedType.U1)] bool flag2);

    // GW::UI::SetPreference | value1: enum GW::UI::NumberPreference (as int)
    [LibraryImport(DllName, EntryPoint = "SetPreference_Number")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetPreference_Number(int value1, uint value2);

    // GW::UI::SetPreference | value1: enum GW::UI::StringPreference (as int)
    [LibraryImport(DllName, EntryPoint = "SetPreference_String")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetPreference_String(int value1, ushort* ptr2);

    // GW::Chat::SetSenderColor
    [LibraryImport(DllName, EntryPoint = "SetSenderColor")]
    internal static partial uint SetSenderColor(Channel channel1, uint value2);

    // GW::Chat::SetTimestampsColor
    [LibraryImport(DllName, EntryPoint = "SetTimestampsColor")]
    internal static partial void SetTimestampsColor(uint value);

    // GW::Chat::SetTimestampsFormat
    [LibraryImport(DllName, EntryPoint = "SetTimestampsFormat")]
    internal static partial void SetTimestampsFormat([MarshalAs(UnmanagedType.U1)] bool flag1, nint ptr2);

    // GW::UI::SetWindowPosition | value1: enum GW::UI::WindowID (as int) | windowPosition2: TODO: map struct GW::UI::WindowPosition
    // [LibraryImport(DllName, EntryPoint = "SetWindowPosition")]
    // [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetWindowPosition(int value1, WindowPosition* windowPosition2);

    // GW::UI::SetWindowVisible | value1: enum GW::UI::WindowID (as int)
    [LibraryImport(DllName, EntryPoint = "SetWindowVisible")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SetWindowVisible(int value1, [MarshalAs(UnmanagedType.U1)] bool flag2);

    // GW::Map::SkipCinematic
    [LibraryImport(DllName, EntryPoint = "SkipCinematic")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SkipCinematic();

    // GW::Trade::SubmitOffer
    [LibraryImport(DllName, EntryPoint = "SubmitOffer")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool SubmitOffer(uint value);

    // GW::Chat::ToggleTimestamps
    [LibraryImport(DllName, EntryPoint = "ToggleTimestamps")]
    internal static partial void ToggleTimestamps([MarshalAs(UnmanagedType.U1)] bool flag);

    // GW::Map::Travel | value1: enum GW::Constants::MapID (as int)
    [LibraryImport(DllName, EntryPoint = "TravelByDistrict")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool TravelByDistrict(int value1, District district2, int value3);

    // GW::Map::Travel | value1: enum GW::Constants::MapID (as int)
    [LibraryImport(DllName, EntryPoint = "TravelByRegion")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool TravelByRegion(int value1, ServerRegion serverRegion2, int value3, Language language4);

    // GW::GuildMgr::TravelGH | gHKey: TODO: map struct GW::GHKey
    // [LibraryImport(DllName, EntryPoint = "TravelGH")]
    // [return: MarshalAs(UnmanagedType.U1)] internal static partial bool TravelGH(GHKey gHKey);

    // GW::UI::UInt32ToEncStr
    [LibraryImport(DllName, EntryPoint = "UInt32ToEncStr")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool UInt32ToEncStr(uint value1, ushort* ptr2, uint value3);

    // GW::CameraMgr::UnlockCam
    [LibraryImport(DllName, EntryPoint = "UnlockCam")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool UnlockCam([MarshalAs(UnmanagedType.U1)] bool flag);

    // GW::CameraMgr::UpdateCameraPos
    [LibraryImport(DllName, EntryPoint = "UpdateCameraPos")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool UpdateCameraPos();

    // GW::Items::UseItem
    [LibraryImport(DllName, EntryPoint = "UseItem")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool UseItem(Item* item);

    // GW::Items::UseItemByModelId
    [LibraryImport(DllName, EntryPoint = "UseItemByModelId")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool UseItemByModelId(uint value1, int value2, int value3);

    // GW::SkillbarMgr::UseSkill
    [LibraryImport(DllName, EntryPoint = "UseSkill")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool UseSkill(uint value1, uint value2);

    // GW::SkillbarMgr::UseSkillByID
    [LibraryImport(DllName, EntryPoint = "UseSkillByID")]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool UseSkillByID(uint value1, uint value2);

    // GW::Items::WithdrawGold
    [LibraryImport(DllName, EntryPoint = "WithdrawGold")]
    internal static partial uint WithdrawGold(uint value);

    // GW::Chat::WriteChat
    [LibraryImport(DllName, EntryPoint = "WriteChat")]
    internal static partial void WriteChat(Channel channel1, ushort* ptr2, nint ptr3, [MarshalAs(UnmanagedType.U1)] bool flag4);

    // GW::Chat::WriteChatEnc
    [LibraryImport(DllName, EntryPoint = "WriteChatEnc")]
    internal static partial void WriteChatEnc(Channel channel1, ushort* ptr2, nint ptr3, [MarshalAs(UnmanagedType.U1)] bool flag4);
}
